// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uno_API.Data;

#nullable disable

namespace Uno_API.Migrations
{
    [DbContext(typeof(UnoDbContext))]
    [Migration("20260731195645_AddPassengerTable")]
    partial class AddPassengerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uno_API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TourId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Uno_API.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Uno_API.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Uno_API.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransportCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportCompanyId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRate = 50m,
                            Name = "John Doe",
                            PhoneNumber = "123-456-7890",
                            TransportCompanyId = 1
                        });
                });

            modelBuilder.Entity("Uno_API.Models.Excursion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Excursions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "City Tour",
                            Price = 30m,
                            SalePrice = 50m,
                            Type = "Half Day"
                        });
                });

            modelBuilder.Entity("Uno_API.Models.ExcursionVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExcursionId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExcursionId");

                    b.HasIndex("VendorId");

                    b.ToTable("ExcursionVendors");
                });

            modelBuilder.Entity("Uno_API.Models.Guide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRate = 100m,
                            Language = "English",
                            Name = "Jane Smith",
                            PhoneNumber = "098-765-4321"
                        });
                });

            modelBuilder.Entity("Uno_API.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DoubleRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SingleRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.Property<decimal>("TripleRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TwinRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("Uno_API.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromVAT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSimpleView")
                        .HasColumnType("bit");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Uno_API.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pax")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Uno_API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ApproxBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectStatusId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Uno_API.Models.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Draft",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Planning",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Active",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "On Hold",
                            OrderIndex = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Completed",
                            OrderIndex = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cancelled",
                            OrderIndex = 6
                        });
                });

            modelBuilder.Entity("Uno_API.Models.SalesTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesRepId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("SalesTrackers");
                });

            modelBuilder.Entity("Uno_API.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCost")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpandable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevenue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classification = "Standard",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Hotel",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 2,
                            Classification = "Standard",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Flight",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 3,
                            Classification = "Standard",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Transport",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 4,
                            Classification = "Standard",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Guide",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 5,
                            Classification = "Standard",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Driver",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 6,
                            Classification = "Extra",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Excursion",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 7,
                            Classification = "Extra",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Tour Package Fee",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 8,
                            Classification = "Extra",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Client Flat Invoice",
                            Type = "Revenue"
                        },
                        new
                        {
                            Id = 9,
                            Classification = "Other",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Parking",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 10,
                            Classification = "Other",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "Tips",
                            Type = "Expense"
                        },
                        new
                        {
                            Id = 11,
                            Classification = "Other",
                            IsActive = true,
                            IsBase = false,
                            IsCost = false,
                            IsExpandable = false,
                            IsOperational = false,
                            IsRevenue = false,
                            Name = "City Tax",
                            Type = "Revenue"
                        });
                });

            modelBuilder.Entity("Uno_API.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdultRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArrivalFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChildRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<string>("DepartureFlight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InfantRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Infants")
                        .HasColumnType("int");

                    b.Property<int>("Pax")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TourCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TourStatusId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Uno_API.Models.TourService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExcursionId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GuideId")
                        .HasColumnType("int");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsRevenue")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RoomCount")
                        .HasColumnType("int");

                    b.Property<string>("RoomType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ServiceEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAirport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TotalNights")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<int?>("TransportCompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceCategoryId");

                    b.HasIndex("TourId");

                    b.ToTable("TourServices");
                });

            modelBuilder.Entity("Uno_API.Models.TourStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TourStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Draft",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Proposal",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Confirmed",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "In Progress",
                            OrderIndex = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Completed",
                            OrderIndex = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cancelled",
                            OrderIndex = 6
                        });
                });

            modelBuilder.Entity("Uno_API.Models.TransportCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FleetSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransportCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactInfo = "info@transport.com",
                            DailyRate = 150m,
                            FleetSize = 15,
                            Name = "Sample Transport Co."
                        });
                });

            modelBuilder.Entity("Uno_API.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contact = "vendor@test.com",
                            Name = "Sample Vendor",
                            ServiceType = "Catering"
                        });
                });

            modelBuilder.Entity("Uno_API.Models.Booking", b =>
                {
                    b.HasOne("Uno_API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uno_API.Models.Tour", "Tour")
                        .WithMany("Bookings")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Uno_API.Models.Collection", b =>
                {
                    b.HasOne("Uno_API.Models.Booking", "Booking")
                        .WithMany("Collections")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Uno_API.Models.Driver", b =>
                {
                    b.HasOne("Uno_API.Models.TransportCompany", "TransportCompany")
                        .WithMany("Drivers")
                        .HasForeignKey("TransportCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TransportCompany");
                });

            modelBuilder.Entity("Uno_API.Models.ExcursionVendor", b =>
                {
                    b.HasOne("Uno_API.Models.Excursion", "Excursion")
                        .WithMany("ExcursionVendors")
                        .HasForeignKey("ExcursionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uno_API.Models.Vendor", "Vendor")
                        .WithMany("ExcursionVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Excursion");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Uno_API.Models.Invoice", b =>
                {
                    b.HasOne("Uno_API.Models.Tour", "Tour")
                        .WithMany("Invoices")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Uno_API.Models.Passenger", b =>
                {
                    b.HasOne("Uno_API.Models.Tour", "Tour")
                        .WithMany("Passengers")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Uno_API.Models.Project", b =>
                {
                    b.HasOne("Uno_API.Models.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uno_API.Models.ProjectStatus", "ProjectStatus")
                        .WithMany()
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ProjectStatus");
                });

            modelBuilder.Entity("Uno_API.Models.SalesTracker", b =>
                {
                    b.HasOne("Uno_API.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Uno_API.Models.Tour", b =>
                {
                    b.HasOne("Uno_API.Models.Project", "Project")
                        .WithMany("Tours")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uno_API.Models.TourStatus", "TourStatus")
                        .WithMany()
                        .HasForeignKey("TourStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TourStatus");
                });

            modelBuilder.Entity("Uno_API.Models.TourService", b =>
                {
                    b.HasOne("Uno_API.Models.ServiceCategory", "ServiceCategory")
                        .WithMany()
                        .HasForeignKey("ServiceCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Uno_API.Models.Tour", "Tour")
                        .WithMany("TourServices")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceCategory");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Uno_API.Models.Booking", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Uno_API.Models.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Uno_API.Models.Excursion", b =>
                {
                    b.Navigation("ExcursionVendors");
                });

            modelBuilder.Entity("Uno_API.Models.Project", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("Uno_API.Models.Tour", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Invoices");

                    b.Navigation("Passengers");

                    b.Navigation("TourServices");
                });

            modelBuilder.Entity("Uno_API.Models.TransportCompany", b =>
                {
                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("Uno_API.Models.Vendor", b =>
                {
                    b.Navigation("ExcursionVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
